---
abstract: 'Establish an ISA relationship with base classes at compile time'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.40'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: parent
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.006'
resources:
  repository: git://github.com/Corion/parent.git
version: '0.238'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
