# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         parent
version:      0.222
version_from: lib/parent.pm
installdirs:  site
requires:
    Test::More:                    0.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
